/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oracleoppgave4;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author staale andre
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtPersonnr = new javax.swing.JTextField();
        txtFornavn = new javax.swing.JTextField();
        txtEtternavn = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtPostnr = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtRegnr = new javax.swing.JTextField();
        txtBilmerke = new javax.swing.JTextField();
        txtBilmodell = new javax.swing.JTextField();
        txtRegAr = new javax.swing.JTextField();
        txtEier = new javax.swing.JTextField();
        butRegBil = new javax.swing.JButton();
        butFinnBiler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Registrer ny person");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPersonnr.setText("Fnr");

        txtFornavn.setText("Fornavn");

        txtEtternavn.setText("Etternavn");

        txtAdresse.setText("Adresse");

        txtPostnr.setText("Postnr");

        jButton2.setText("Finn Person");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtRegnr.setText("Regnr");

        txtBilmerke.setText("Bilmerke");

        txtBilmodell.setText("Bilmodell");

        txtRegAr.setText("Regår");

        txtEier.setText("Eier");

        butRegBil.setText("Registrer ny bil");
        butRegBil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegBilActionPerformed(evt);
            }
        });

        butFinnBiler.setText("Finn biler");
        butFinnBiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFinnBilerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPostnr)
                                .addGap(43, 43, 43)))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAdresse, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEtternavn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFornavn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPersonnr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBilmodell)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRegAr)
                        .addGap(90, 90, 90))
                    .addComponent(txtEier)
                    .addComponent(butRegBil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRegnr)
                    .addComponent(txtBilmerke))
                .addGap(450, 450, 450))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(butFinnBiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRegnr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBilmerke, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBilmodell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegAr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEier, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRegBil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPersonnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFornavn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEtternavn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostnr, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(butFinnBiler))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
            int personnr = Integer.parseInt(txtPersonnr.getText());
            String fornavn = txtFornavn.getText();
            String etternavn = txtEtternavn.getText();
            String adresse = txtAdresse.getText();
            int postnr = Integer.parseInt(txtPostnr.getText());
 
 control.control.regNyEier(personnr,fornavn,etternavn,adresse,postnr);
 }catch(Exception ex){JOptionPane.showMessageDialog(null,ex.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // TODO add your handling code here:private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
 long nr = Long.parseLong(JOptionPane.showInputDialog("Skriv fnr til personen du søker: "));
 String navn = control.control.getNavn(nr);
 JOptionPane.showMessageDialog(null,"Navn: " + navn);
 if(navn !=null) JOptionPane.showMessageDialog(null,"Navn: " + navn);
 else JOptionPane.showMessageDialog(null,"Kan ikke finne fnr");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butRegBilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegBilActionPerformed
       try{
       String regnr = txtRegnr.getText();
       String bilmerke = txtBilmerke.getText();
       String bilmodell = txtBilmodell.getText();
       int regår = Integer.parseInt(txtRegAr.getText());
       int eier = Integer.parseInt(txtEier.getText());
       control.control.regNyBil(regnr, bilmerke, bilmodell, regår, eier);
       }catch(Exception ex){JOptionPane.showMessageDialog(null, ex.getMessage());}
    }//GEN-LAST:event_butRegBilActionPerformed

    private void butFinnBilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFinnBilerActionPerformed
        String uttekst = "";
 String regnr, bilmodell,bilmerke,regar;
 long nr = Long.parseLong(JOptionPane.showInputDialog("Skriv inn fnr"));
 try{
     
 ResultSet rs = control.control.getBiler(nr);
 while(rs.next()) {
 regnr = rs.getString(1);
 bilmerke = rs.getString(2);
 bilmodell = rs.getString(3);
 regar = rs.getString(4);
 uttekst = uttekst+regnr+", "+bilmerke+", "+bilmodell+", "+regar+"\n";
 }
 JOptionPane.showMessageDialog(null,uttekst);
rs.close();
 }catch(HeadlessException | NumberFormatException | SQLException ex){JOptionPane.showMessageDialog(null,ex.getMessage());}
    }//GEN-LAST:event_butFinnBilerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butFinnBiler;
    private javax.swing.JButton butRegBil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtBilmerke;
    private javax.swing.JTextField txtBilmodell;
    private javax.swing.JTextField txtEier;
    private javax.swing.JTextField txtEtternavn;
    private javax.swing.JTextField txtFornavn;
    private javax.swing.JTextField txtPersonnr;
    private javax.swing.JTextField txtPostnr;
    private javax.swing.JTextField txtRegAr;
    private javax.swing.JTextField txtRegnr;
    // End of variables declaration//GEN-END:variables
}
